# Generated by Django 5.2.5 on 2025-09-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du site')),
                ('entite', models.CharField(max_length=200, verbose_name='Entité en charge')),
                ('adresse', models.CharField(max_length=300, verbose_name='Adresse')),
                ('arrondissement', models.CharField(blank=True, max_length=10, null=True, verbose_name='Arrodissement')),
            ],
        ),
    ]
