# Generated by Django 5.2.5 on 2025-09-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goeco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclerieRessourcerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(max_length=255, verbose_name='Opérateur')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code postal')),
            ],
            options={
                'verbose_name': "Recyclerie/ Ressourcerie/ Point d'apport volontaire",
                'verbose_name_plural': "Recycleries/ Ressourceries/ Points d'apport volontaire",
            },
        ),
    ]
