# Generated by Django 5.2.5 on 2025-10-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goeco', '0002_recyclerieressourcerie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composteur',
            name='adresse',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Adresse'),
        ),
    ]
