# Generated by Django 5.2.5 on 2025-10-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goeco', '0003_alter_composteur_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composteur',
            name='adresse',
            field=models.CharField(default='Adresse inconnue', max_length=300, verbose_name='Adresse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='composteur',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du site'),
        ),
    ]
